model_name: RNNGRU

model_path: models/RNNGRU/2019-11-12-11:27:57/final_model.h5  # RNN
dwi_path: subjects/ismrm_gt/fod_norm_125.nii.gz
prior_path: subjects/ismrm_gt/tensor_V1_125.nii.gz
seed_path: scoring/scoring_data/seeds/seeds_from_wm_100.trk
term_path: subjects/ismrm_gt/wm_mask_125.nii.gz

thresh: 0.1

step_size: 0.25
max_steps: 800
batch_size: 20000
out_dir:
