model_name: RNN

model_path: models/rnn/2019-11-06-10:53:46/final_model.h5  # RNN
#model_path: models/RNNLSTM/2019-11-07-15:46:10/final_model.h5  # LSTM
dwi_path: subjects/ismrm_gt/fod_norm_125.nii.gz
prior_path: subjects/ismrm_gt/tensor_V1_125.nii.gz
seed_path: scoring/scoring_data/seeds/seeds_from_fibers_100.trk
term_path: subjects/ismrm_gt/wm_mask_125.nii.gz

thresh: 0.1

predict_fn: mean # choices=["mean", "sample"]
step_size: 0.25
max_steps: 400
batch_size: 512
out_dir: