model_name: Detrack
model_type: conditional

action: training

optimizer: Adam
opt_params: 
  learning_rate: 0.0001
  clipnorm: 10.0

epochs: 10
batch_size: 512
shuffle: False

callbacks:
  TBSummaries:
    update_freq: 256
    out_dir: None

out_dir: None

train_path: /local/tract/conditional_samples/992774/2019-11-20-14:42:16/  # 0.2 keep
eval_path: /local/home/vwegmayr/ijcv19/subjects/917255/samples/2019-11-11-10:42:51/samples.npz  # 0.001 keep

