model_name: RNNGRU

temperature:

optimizer: Adam
opt_params: 
  learning_rate: 0.0001
  clipnorm: 10.0

epochs: 10
batch_size: 128
shuffle: False

train_path: /local/tract/rnn_samples/992774/2019-11-19-06:15:58/  # 0.2 keep
eval_path: /local/tract/rnn_samples/992774/2019-11-19-14:17:59/ # 0.05 keep

callbacks:
  RNNResetCallBack:
    reset_batches:
  ModelCheckpoint:
    filepath:

out_dir: None
