model_name: RNNLSTM

temperature:

optimizer: Adam
opt_params: 
  learning_rate: 0.0001
  clipnorm: 10.0

epochs: 10
batch_size: 128
shuffle: False

train_path: /local/tract/rnn_samples/992774/2019-11-12-11:18:30/samples.npz
eval_path: /local/tract/rnn_samples/644044/2019-11-12-10:41:22//samples.npz

callbacks:
  RNNResetCallBack:
    reset_batches:
  ModelCheckpoint:
    filepath:

out_dir: None
