model_name: RNNLSTM

temperature:

optimizer: Adam
opt_params: 
  learning_rate: 0.0001
  clipnorm: 10.0

epochs: 10
batch_size: 50
shuffle: False

train_path: subjects/644044/small_samples/2019-11-06-10:10:51/samples.npz

callbacks:
  RNNResetCallBack:

out_dir: None