model_name: RNNGRUEntrack
model_type: conditional

action: training

temperature: 0.04

optimizer: Adam
opt_params:
  learning_rate: 0.0001
  clipnorm: 10.0

epochs: 10
batch_size: 128
shuffle: False

callbacks:
  RunningWindowLogger:
    metrics: ["kappa_mean", "fvm_mean_neg_dot_prod"]
    window_size: 32
  AutomaticTemperatureSchedule:
    temperature: None
    T_stop: 0.005
    decay: 0.99
    tol: 0.04
    min_lr: 0.0001
    n_checkpoints: 10
    out_dir: None
  RNNResetCallBack:
    reset_batches:

out_dir: None

# W0001
train_path: /local/tract/rnn_samples/992774/2019-11-12-11:18:30/samples.npz
eval_path: /local/tract/rnn_samples/644044/2019-11-12-10:41:22//samples.npz
