model_name: Trackifier

optimizer: Adam
opt_params:
  learning_rate: 0.0001
  clipnorm: 10.0

epochs: 10
batch_size: 128
shuffle: False

train_path: /local/home/vwegmayr/ijcv19/subjects/992774/samples/2019-11-11-19:37:28/samples.npz
eval_path: /local/home/vwegmayr/ijcv19/subjects/917255/samples/2019-11-11-10:42:51/samples.npz
bvec_path: /local/home/vwegmayr/ijcv19/subjects/992774/bvecs_input

callbacks:
  ModelCheckpoint:
    filepath:

out_dir: None
