model_name: Trackifier

optimizer: Adam
opt_params:
  learning_rate: 0.0001
  clipnorm: 10.0

epochs: 10
batch_size: 128
shuffle: False

train_path: /local/tract/conditional_samples/992774/2019-11-20-14:42:16/  # 0.2 keep
eval_path: /local/tract/conditional_samples/644044/2019-11-19-15:39:21/ # 0.01 keep
bvec_path: subjects/992774/bvecs_input

callbacks:
  ModelCheckpoint:
    filepath:

out_dir: None
