trk_path: subjects/ismrm_basic/marked_fibers/2019-11-25=22:06:30/marked.trk
filter_name: log_prob_sum
percentile: 10 # percentile
apply_k: False

score: True
python2: /local/home/abahrein/.envs/scoring/bin/activate
