action: mark
model_name: Entrack

model_path: models/model_T=0.0023.h5
dwi_path: subjects/ismrm_basic/fod_norm_125.nii.gz
trk_path: subjects/ismrm_basic/predicted_fibers/2019-11-14-09:36:59/2019-11-14-09:36:59.trk
