action: mark

model_path: models/Entrack/conditional/2019-11-21/12:42:23/final_model.h5
dwi_path: subjects/ismrm_gt/fod_norm_125.nii.gz
trk_path: subjects/ismrm_gt/predicted_fibers/2019-11-14-17:10:26/2019-11-14-17:10:26_s=0.0_n=same.trk